### DISCUSSION TITLE
Does spark operator support dynamic resource allocation?

### DISCUSSION THREAD

**Discussion by paulpaul1076** [stackabletech/spark-k8s-operator#312] [Q&A]
I haven't seen any mention of dynamic resource  allocation for spark jobs in stackable docs. Is it supported? Or is it more of a "use it at your own risk" type of thing?

Thanks.

**Comment by adwk67** [comment]
It is supported partially, in the sense that you can set min/max CPU and a memory limit for the executors defined for your SparkApplication. What we don't support is a dynamic number of executors. We may do in the future but there are a number of factors that need to be considered:

- the Kubernetes-specific Spark issue is still [open](https://issues.apache.org/jira/browse/SPARK-24432) and I think we would prefer to wait until this has been completed. See some of the provisos mentioned [here](https://spark.apache.org/docs/latest/running-on-kubernetes.html#stage-level-scheduling-overview).
- the Spark [issue](https://issues.apache.org/jira/browse/SPARK-27963)  (see also the [PR](https://github.com/apache/spark/pull/24817)) that enhances shuffle-tracking allows an initial number if executors to be set, but then things can complicated when workflow distribution needs to accomodate other settings such as affinities etc.

So...the k8s "paradigm" moves away from a cluster running a static number of nodes to pods-on-demand, and resources for these pods can be set on a per-Job basis: is that sufficient for your use-cases? If not, what specific scenario are you looking at that could be improved by dynamic allocation?

**Reply by paulpaul1076** [reply]
@adwk67 is there an example of how to set min/max CPU and memory limit? On the internet I've only seen examples of min/max executor numbers. So, I wouldn't even know the name of the setting.

You say that dynamic number of executors isn't supported, but yesterday I literally tried setting `spark.dynamicAllocation.minExecutors` and `spark.dynamicAllocation.maxExecutors` and I saw the number of executors increase and decrease. How is this possible when you say that it isn't supported?

These are the settings I set:

```
    spark.shuffle.service.enabled: 'false'
    spark.dynamicAllocation.enabled: 'true'
    spark.dynamicAllocation.executorIdleTimeout: '5'
    spark.dynamicAllocation.shuffleTracking.enabled: 'true'
    spark.dynamicAllocation.initialExecutors: '1'
    spark.dynamicAllocation.minExecutors: '0'
    spark.dynamicAllocation.maxExecutors: '7'
```

You can see the screenshot below, it shows that the number of executors would change as my spark application was running. (I was checking it with `kubectl get pods`)

![Screenshot 2023-11-28 130341](https://github.com/stackabletech/spark-k8s-operator/assets/4533296/ee21bb4e-5911-4452-b616-8273aa504214)

**Reply by adwk67** [reply]
Thanks for your reply and the details you share. Sorry, I wasn't clear: dynamic pods are not **officially** supported by us, even if it works by passing spark configuration settings straight through to the spark-submit command (which is what we do with things listed under `sparkConf`). For simple cases this may be fine but we have not tested it with other features such as Pod availability, Pod disruption budgets and affinities and so can't (at this time) give any guidelines or guarantees.

Regarding setting resources: you can look at [this](https://github.com/stackabletech/spark-k8s-operator/tree/main/tests/templates/kuttl/resources) integration test to see how they are specified and what is expected.

**Reply by paulpaul1076** [reply]
Thanks.

I see `spark.kubernetes.driver.request.cores`, `spark.kubernetes.driver.limit.cores`, `spark.kubernetes.executor.request.cores`, `spark.kubernetes.executor.limit.cores`. I guess that's the way you set min/max for cores?

As for memory min/max, I saw this:

```
spec:
  containers:
    - name: spark-submit
      resources:
        limits:
          cpu: 400m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
```

But it also specifies cores, too. So, which one will eventually be used? The one from Spark config, or this one? What's the priority?

In the yaml files I've used for submitting spark applications I also have this:

```
  driver:
    resources:
      cpu:
        min: '250m'
        max: "1"
      memory:
        limit: '1Gi'
    volumeMounts:
      - name: job-deps
        mountPath: /dependencies/jars
  executor:
    instances: 4
    resources:
      cpu:
        min: '250m'
        max: "1"
      memory:
        limit: '1Gi'
    volumeMounts:
      - name: job-deps
        mountPath: /dependencies/jars
```

I guess it's yet another place where this can be specified? I can see the min/max for cpu here, but how would I specify the min/max for memory? I can see `limit` there, I guess `limit`=`max`? How would I specify `min`? Through the `request` keyword?

Btw, do configs like `spark.kubernetes.driver.request.cores` support the `400m` syntax? Or can only natural numbers be used there?
