### DISCUSSION TITLE
How to properly specify s3 credentials for mainApplicationFile in Spark operator?

### DISCUSSION THREAD

**Discussion by paulpaul1076** [stackabletech/spark-k8s-operator#328] [Q&A] [answered]
I have this mainApplicationFile config:
```
mainApplicationFile: s3a://obs-zdp-warehouse-stage-mz/firestarter-1.0.0.jar
```
I specified an s3connection for it:

```
  s3connection:
    inline:
      host: url.....
      port: 443
      accessStyle: Path
      credentials:
        secretClass: s3-credentials-class
 ```       
 
 I also created 2 files:
 
 ```
1) s3-credentials.yml:
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  labels:
    secrets.stackable.tech/class: s3-credentials-class
stringData:
  accessKey: *****
  secretKey: *****
  ```
  ```
2)  s3-credentials-class.yml

apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: s3-credentials-class
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
 ```
        
 But with this config there's nothing happening, the pod that's supposed to start the spark application is in stuck "Pending" state.
 
 
 Optional info:
 
 I previously used (and it worked):
 
 ```
 spec:
   env:
     -name:AWS_ACCESS_KEY_ID
     value:"***"
     -name:AWS_SECRET_ACCESS_KEY
     value:"***"
```

But now, for some reason it doesn't work properly when using multiple buckets in my Spark application. For some reason it applies these keys to all buckets that I use and I get an error, saying that my access and secret key is wrong.

I did specify 
```
spark.hadoop.fs.s3a.bucket.bucket1.access.key
spark.hadoop.fs.s3a.bucket.bucket1.secret.key

spark.hadoop.fs.s3a.bucket.bucket2.access.key
spark.hadoop.fs.s3a.bucket.bucket2.secret.key|
```

in my spark config, but it still seems to use the keys from env for some weird reason.

I tried:
```
spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider
spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
```
Any ideas on how to resolve this?
