### DISCUSSION TITLE
"java.net.NoRouteToHostException: No route to host (Host unreachable)" when connecting to Hive metastore from Spark

### DISCUSSION THREAD

**Discussion by paulpaul1076** [stackabletech/spark-k8s-operator#329] [Q&A] [answered]
When I try to connect to hive metastore from spark 3.5.0 operator, I get this exception:

[New Text Document.txt](https://github.com/stackabletech/spark-k8s-operator/files/13739369/New.Text.Document.txt)

It worked previously in Spark 3.4.0. Do you know why this could  be? And what is the easiest way to check connectivity from your spark pods to hive metastore pods?

Thanks!

More info:

Stackable version of hive metastore is 23.7.0
Stackable version of spark is 23.11.0

Could this be the problem?

**Comment by adwk67** [comment]
I've had a look at the list of [breaking changes](https://docs.stackable.tech/home/stable/release-notes#_breaking_changes) in the last release and there are none that relate to Hive resource definitions per se. The intention with SDP releases is to issue operators in a version that have been tested and verified to work together, so mixing the operator release versions is not recommended. Without having any more information it looks as though this is network related. Can you provide the hive metastore resource definition?

**Reply by paulpaul1076** [reply]
This is it:
```
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-obs
  namespace: trino
  annotations:
    vault.security.banzaicloud.io/vault-addr: 'https://vault.com'
    vault.security.banzaicloud.io/vault-path: kubernetes-stage
    vault.security.banzaicloud.io/vault-role: role
    vault.security.banzaicloud.io/vault-skip-verify: 'true'
    vault.security.banzaicloud.io/inline-mutation: "true"
spec:
  image:
    productVersion: 3.1.3
    stackableVersion: 23.7.0
```

I guess we will try to match its version with 23.11.0 of spark operator.
