### ISSUE TITLE
Research: Data locality with spark-k8s

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#120]
As a user I want to have a plan/outline/overview of how to write spark jobs that read data from HDFS nodes within k8s (this will possibly overlap or support #117).

This is a research ticket: as a result we will able to

- understand pros/cons
- be able to estimate implementation effort
- define specific implementation ticket(s)

**Comment by adwk67** [comment]
Data locality with spark-on-kubernetes is not available by default: this is not surprising as compute and storage is handled differently in k8s compared to HDFS. 

#### Background/context
- Build K8s with [this](https://github.com/apache-spark-on-k8s/kubernetes-HDFS) plugin: see [also](https://stackoverflow.com/a/70112542/110933)
  - Talk: https://www.databricks.com/session/hdfs-on-kubernetes-lessons-learned
  - Slides: https://www.slideshare.net/databricks/hdfs-on-kuberneteslessons-learned-with-kimoon-kim
- [Best practices ](https://www.databricks.com/session_na20/running-apache-spark-on-kubernetes-best-practices-and-pitfalls)running Spark on k8s
  - blog [post](https://spot.io/blog/setting-up-managing-monitoring-spark-on-kubernetes/) here, plus [associated](https://spot.io/blog/the-pros-and-cons-of-running-apache-spark-on-kubernetes/) [articles](https://spot.io/blog/apache-spark-performance-benchmarks-show-kubernetes-has-caught-up-with-yarn/)
  - nothing really on data co-locality
  - recommendations to use SSD disks
- CERN event 2018
  - slides [here](https://indico.cern.ch/event/754246/contributions/3124983/attachments/1708398/2753279/Spark-Kubernetes-Training-2018.pdf)
  - > "Without data locality, network can be a
serious problem/bottleneck"
  - ...but no recommendations (slide 50)
  - recommend native storage connectors (EOS, Kafka) for data processing (slide 49)
- Use [Alluxio](https://github.com/Alluxio/alluxio) with Spark on K8s
  - 2020 [slides](https://www.cncf.io/wp-content/uploads/2020/08/Alluxio-K8s-locality-CNCF-Jan-2020.pdf)

#### Possible approaches

**Comment by adwk67** [comment]
#### Alluxio summary
The following were tested / verified using the documentation [here](https://docs.alluxio.io/os/user/stable/en/overview/Getting-Started.html) and [here](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html):
- quickstart local setup
- k8s cluster setup with multiple masters and an embedded journal (but no UFS / underlying file-system)
- k8s cluster setup with a single master, an embedded journal and HDFS as the UFS
  - successful tests verifying read / write operations with HDFS
 
![image](https://user-images.githubusercontent.com/1712947/186929019-a76a3659-e3cf-4ec7-9748-da97ff9acc3c.png)
![image](https://user-images.githubusercontent.com/1712947/186929290-01a9ee2f-1bc4-4110-a390-8717c0b5eff6.png)

##### Notes
- installations can use either helm or kubectl. The kubectl .yaml files can be generated directly from the helm chart using a provided script (so that the helm chart is the single source of truth: users can adapt or provide their own kubectl files). Kubectl offers more fine-grained control and was the chosen option.
- several examples require RWX PVCs for the worker volumes. - worker pods are deployed with DaemonSet, for which separate PVs cannot be defined for each worker pod. A single local or hostPath PV must be used, so that the worker will translate it to the local path. Where this is not possible - e.g. with a KinD cluster - the cluster has to be set up to allow hostPath storage ([this](https://github.com/stackabletech/spark-k8s-operator/blob/main/kind/spark-k8s-kind-cluster-yaml) script was used).
- the guide states that the journal must be formatted: this can be done by adding an initContainer to the `alluxio-master-statefulset.yaml` file:
```
      initContainers:
        - name: journal-format
          image: alluxio/alluxio:2.8.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
          command: ["alluxio","formatJournal"]
          envFrom:
            - configMapRef:
                name: alluxio-config
          volumeMounts:
            - name: alluxio-journal
              mountPath: /journal
```
- as mentioned above, the PVC definition in `alluxio-worker-daemonset.yaml` can be replaced with hostPath:
```
 persistentVolumeClaim:
   claimName: "alluxio-worker-domain-socket"
// replaced with this:
 hostPath:
   path: /tmp/kind-shared-volume/alluxio-domain
   type: DirectoryOrCreate
```
- the [guide](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html#basic-setup) states that:
> Alluxio Docker containers will run as non-root user alluxio with UID 1000 and GID 1000 by default.
  - this means that HDFS permissions have to be changed to allow this user read/write access (or the user has to be changed)
- a compute layer (e.g. Spark) would then address alluxio URLs rather than the UFS directly
- Alluxio adds complexity and caching overhead (in that the cache has to be filled and maintained): depending on the use-case this may or may not be more desirable than improving network performance
