### ISSUE TITLE
Compute resources and number of executors are not set

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/spark-k8s-operator#161]
### Affected version

nightly

### Current and expected behavior

Configuring the following compute resources
```
      job:
        resources:
          cpu:
            min: 100m
            max: "1"
          memory:
            limit: 1Gi
      driver:
        resources:
          cpu:
            min: "1"
            max: "2"
          memory:
            limit: 2Gi
        volumeMounts:
          - name: script
            mountPath: /stackable/spark/jobs
      executor:
        instances: 5
        resources:
          cpu:
            min: "4"
            max: "6"
          memory:
            limit: 8Gi
        volumeMounts:
          - name: script
            mountPath: /stackable/spark/jobs
```
I would have expected the following settings (i manually overwrite them to get it working)
```
      sparkConf:
        spark.executor.instances: "5"
        spark.driver.cores: "2"
        spark.driver.memory: "2g"
        spark.kubernetes.driver.request.cores: "1"
        spark.kubernetes.driver.limit.cores: "2"
        spark.executor.cores: "6"
        spark.executor.memory: "8g"
        spark.kubernetes.executor.request.cores: "4"
        spark.kubernetes.executor.limit.cores: "6"
```

Whatever currently is done is way of, e.g. it only spawns 2 executors, executor cpu and memory seem to be the default values and the executor thinks it has a single core.

### Possible solution

Did some prototyping in https://github.com/stackabletech/spark-k8s-operator/pull/160
In a nutshell we need to set all the above mentioned values (can be used as a test case)
* `spark.executor.instances` obviously
* `spark.driver.memory` and `spark.executor.memory` need to be fetched from the memory limit and somehow converted to the Spark memory convention. Special caution is needed as if a user specifies e.g. 8Gi for a executor, Spark will add overhead and the resulting Pods will have a memory limit of `11468Mi`. We want to subtract that overhead and do calculations (and/or set overhead configurations) to achieve the requested 8Gi memory limit of the executor Pods.
* spark.kubernetes.driver.(request|limit).cores and spark.kubernetes.driver.(request|limit).cores can be 1:1 mapped from the CRD i guess
* `spark.driver.cores` and `spark.executor.cores` need to be fetched from the cpu limit, somehow converted to a floating point, rounded up and given as a while positive number
