### ISSUE TITLE
S3 reference inconsistency

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/spark-k8s-operator#162]
### Affected version

nightly

### Current and expected behavior

Currently we have the following CRD
```
    s3bucket:
      inline:
        bucketName: some-dummy-value
        connection:
          reference: spark
```
As we only need to tell s3a the endpoint, credentials etc. but *not* he bucket we should use a S3ConnectionDef as follows:
```
    s3conncetion:
      reference: spark
```

Second inconsistency is in https://github.com/stackabletech/spark-k8s-operator/blob/c47e14951b324e06e717042bf0cf4b3ffb115e03/rust/crd/src/constants.rs#L20-L21
All the operators (and the official concepts docs) use `accessKey` and `secretKey` in the credentials secret.
We need to adopt the spark-k8s operator to adhere to the common convention so that S3Connections can be reused across multiple products.

### Possible solution

* Use S3ConnectionDef rather then S3BucketDef
* Use `accessKey` and `secretKey` rather than `accessKeyId` and `secretAccessKey`
