### ISSUE TITLE
Support for Storage Class on Spark Executors

### ISSUE THREAD

**Issue by zaultooz** [stackabletech/spark-k8s-operator#170]
Hey Stackable Team

Working with your operator for Spark, I would like to be able to configure a Storage Class for the executors. The idea behind the request, is to be able to provide ways for Kubernetes to assign PVCs dynamically for each executor on the nodes they are running on. 

```yaml
executor:
  cores: 1
  instances: 10
  memory: 2048m
  storage:
    storageClass: 'custom-storage-class'
  volumeMounts:
    - name: configs
      path: /etc/spark/configs
```

If I understood it correctly, the executors currently use either the RAM or the root directory for the Kubelet instance as ephemeral storage. This could lead to OOM kill for the executor instance or wait time for I/O on the node if there is a lot of activity on node. I can see on your [docs page](https://docs.stackable.tech/spark-k8s/stable/usage.html) that you can define volumeMounts which looks like are shared across all the instance, suitable for config but less attractive for write cases.

I observed the potential use-case for applying Storage classes to executors while looking an issue where my Spark executors instances would be killed by OOM during the shuffle phase. I believe Spark utilize the disk for storing streamed data until it is ready to use it, however I am not super driven in Spark so it could I have misunderstood their docs.

Please feel free to correct me if any of my assumptions or ideas are incorrect.
