### ISSUE TITLE
Configure node selection

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#3]
As a user of spark-on-k8s I want to be able configure pod affinity and node selection.

The [current documentation](https://spark.apache.org/docs/latest/running-on-kubernetes.html#how-it-works) - for 3.2.1 - indicates that this is possible:

"It is possible to schedule the driver and executor pods on a subset of available nodes through a [node selector](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector) using the configuration property for it. It will be possible to use more advanced scheduling hints like [node/pod affinities](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity) in a future release."

**Comment by fhennig** [comment]
The node selector can be set with the spark config property `spark.kubernetes.node.selector.<identifier>`. That's a low hanging fruit, because it's already a built-in feature. This will be turned into a label selector for the driver and executor pods. 

We could implement that quickly, maybe that's already enough. Affinities are not yet supported, we'd have to built a mechanism ourselves.

**Comment by adwk67** [comment]
Pod affinity removed from description as that will covered in a future spark release.

**Comment by adwk67** [comment]
I've tested this a bit and can confirm the following:

- for self-enclosed jobs (i.e. with no external dependencies) the node can be selected using the `spark.kubernetes.node.selector.<identifier>` configuration setting that be passed through directly to spark via the `sparkConf` list in the `SparkApplication` Resource e.g.
  ```
  sparkConf:
     spark.kubernetes.node.selector.node: "3"
  ```
- for jobs with pod-based dependencies (e.g. volumes), the driver and executors will "follow" the node selection applied to the pod i.e. if we have a `Job` that creates and populates a volume that is used by the `SparkApplication`, then Kubernetes detects this as a dependency and the driver and executor pods will be created on the same node (if we try to use the first approach to assign the driver to another node, we get a pod-affinity-conflict error):
    ```
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: aws-deps
    spec:
      template:
        spec:
          restartPolicy: Never
          nodeSelector:
            node: "1"
          volumes:
            - name: job-deps
    ...
    ```
@fhennig @razvan Shall we close this issue as there is nothing to implement in the code for the two possibilities described above?
