### ISSUE TITLE
Add Spark Iceberg runtime to the spark-k8s image

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/spark-k8s-operator#341]
Spark Iceberg runtime is not included in the Spark distribution and it super useful for anyone interacting with Iceberg tables. It makes sense to me that this should be included in the Stackable spark-k8s Docker image since it is a commonly used component. Including it will allow for Spark SQL interaction with Iceberg tables out of the box.

At the moment I am loading the required library by adding this to my SparkApplication definition:

```
kind: SparkApplication
spec:
  deps:
    packages:
      - org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.4.3
```
