### ISSUE TITLE
Use operator-rs `build_rbac_resources` instead of own implementation

### ISSUE THREAD

**Issue by maltesander** [stackabletech/spark-k8s-operator#499]
## Issue checklist

PR https://github.com/stackabletech/issues/issues/675 fixed a bug in operator-rs `build_rbac_resources` to improve ServiceAccount / RoleBinding deployment.

The spark-k8s operator uses its own method `build_history_role_serviceaccount` (only required for the history server). Although that method does not introduce the bug fixed in https://github.com/stackabletech/issues/issues/675, it differs in terms of naming the ServiceAccount and RoleBinding (missing suffixes `-serviceaccount` and `rolebinding` respectivly).

This should be consolidated.

A quick test lead to label differences of the ServiceAccount / RoleBinding. This needs investigation.

Generated labels using the spark-k8s-ops `build_history_role_serviceaccount`:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: spark-history
    app.kubernetes.io/managed-by: spark.stackable.tech_history
    app.kubernetes.io/name: spark-k8s
    app.kubernetes.io/role-group: history
    app.kubernetes.io/version: 3.5.2-stackable0.0.0-dev
    stackable.tech/vendor: Stackable
  name: spark-history-serviceaccount
  ...
```

vs generated via operator-rs `build_rbac_resources`:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2024-11-24T12:43:23Z"
  labels:
    app.kubernetes.io/instance: spark-history
    app.kubernetes.io/managed-by: spark.stackable.tech_history
    app.kubernetes.io/name: spark-k8s
  name: spark-history-serviceaccount
  ...
```
