### ISSUE TITLE
cannot configure a secret class only for tls validation

### ISSUE THREAD

**Issue by razvan** [stackabletech/spark-k8s-operator#529]
### Affected Apache Spark-on-Kubernetes version

probably all

### Current and expected behavior

Given a secret configuration like this:

```yaml
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
 name: s3-ca-class
spec:
 backend:
   k8sSearch:
     searchNamespace:
       pod: {}
---
kind: Secret
apiVersion: v1
metadata:
 name: s3-ca
 namespace: stackable-operators
 labels:
   secrets.stackable.tech/class: s3-ca-class
data:
 ca.crt: ...
type: Opaque
```
and using it for a spark history S3 bucket results in an error:

```
javax.net.ssl|ERROR|21|Thread-3|2025-02-26 15:34:53.208 UTC|null:-1|Fatal (CERTIFICATE_UNKNOWN): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (
5238"throwable" : {
5239sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
5240at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
5241at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
5242at java.base/sun.security.validator.Validator.validate(Unknown Source)
5243at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
5244at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
5245at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
5246at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
5247at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
```

Also clarify why TLS validation is prohibited for applications but not for the history server.

### Would you like to work on fixing this bug?

None
